B 7.0.x leverage composer scripts (#966) (#968)
* Switch to light workflows using scripts
* Use install script
* Determine the branch based on the changelog, if the branch name is problematic

diff --git a/.github/workflows/trigger.yaml b/.github/workflows/trigger.yaml
--- a/.github/workflows/trigger.yaml
+++ b/.github/workflows/trigger.yaml
@@ -1,5 +1,4 @@
 name: Auto trigger on push or pull requests
-# Matrix workflow using re-usable github actions
 
 on:
   pull_request: {}
@@ -22,27 +21,42 @@ jobs:
           else
             REF_TO_CHECK='${{ github.ref }}'
             # shellcheck disable=SC2088
-            LIMIT70="~/defaults/php8.1_mysql5.7_only.yml,"
+            LIMIT70="~/defaults/php8.1_mysql5.7_only.yaml,"
             # shellcheck disable=SC2088
-            LIMIT="~/defaults/php8.2_mysql5.7_only.yml,"
+            LIMIT="~/defaults/php8.2_mysql5.7_only.yaml,"
           fi
           # shellcheck disable=SC2088
           case "${REF_TO_CHECK}" in
-            refs/heads/b-7.0.x*) TESTPLAN="~/defaults/7.0.x.yml,${LIMIT70}~/shop_ce_70x.yml" ;;
-            refs/heads/b-7.1.x*) TESTPLAN="~/defaults/7.1.x.yml,${LIMIT}~/shop_ce.yml" ;;
-            refs/heads/b-7.2.x*) TESTPLAN="~/defaults/7.2.x.yml,${LIMIT}~/shop_ce.yml" ;;
-            refs/heads/b-8.0.x*) TESTPLAN="${LIMIT}~/shop_ce.yml" ;;
+            refs/heads/b-7.0.x*) TESTPLAN="~/defaults/7.0.x.yaml,${LIMIT70}~/shop_ce.yaml" ;;
+            refs/heads/b-7.1.x*) TESTPLAN="~/defaults/7.1.x.yaml,${LIMIT}~/shop_ce.yaml" ;;
+            refs/heads/b-7.2.x*) TESTPLAN="~/defaults/7.2.x.yaml,${LIMIT}~/shop_ce.yaml" ;;
+            refs/heads/b-8.0.x*) TESTPLAN="${LIMIT}~/shop_ce.yaml" ;;
             *)
               echo "Can't match ${REF_TO_CHECK} to a version, can't determine test plan."
               echo "Branch names should start with b-<major>.<minor>.x"
-              exit 1
+              echo "Using the shop changelog to determine the shop version"
+              git clone --depth 2 "${{ github.repositoryUrl }}" --branch "${{ github.ref_name}}" --single-branch .tmp
+              if [ -f .tmp/CHANGELOG-8.0 ]; then
+                TESTPLAN="${LIMIT}~/shop_ce.yaml"
+              elif [ -f .tmp/CHANGELOG-7.2 ]; then
+                TESTPLAN="~/defaults/7.2.x.yaml,${LIMIT}~/shop_ce.yaml"
+              elif [ -f .tmp/CHANGELOG-7.1 ]; then
+                TESTPLAN="~/defaults/7.1.x.yaml,${LIMIT}~/shop_ce.yaml"
+              elif [ -f .tmp/CHANGELOG-7.0 ]; then
+                TESTPLAN="~/defaults/7.0.x.yaml,${LIMIT70}~/shop_ce.yaml"
+              else
+                echo "Could not find any of CHANGELOG-8.0, CHANGELOG-7.2, CHANGELOG-71. or CHANGELOG-7.0"
+                echo "Still can't determine the test plan"
+                exit 1
+              fi
+              rm -rf .tmp
               ;;
           esac
           echo "testplan=${TESTPLAN}" | tee -a "${GITHUB_OUTPUT}"
 
   shop_ce:
     needs: build_testplan
-    uses: oxid-eSales/github-actions/.github/workflows/call-universal_test_workflow.yml@v4
+    uses: oxid-eSales/github-actions/.github/workflows/universal_workflow_light.yaml@v4
     with:
       testplan: ${{ needs.build_testplan.outputs.testplan }}
       runs_on: '"ubuntu-latest"'
